## Latihan

In [3]:
# Membuat array 3 dimensi
# perkalian matriks array

import numpy as np

A = np.array([15, 9, 5])
B = np.array([64, 68, 54])
C = np.array([12, 14, 16])

kali = A * B * C
print(kali)

[11520  8568  4320]


In [5]:
# Pengurangan matrix

import numpy as np 

A = np.array([15, 9, 5])
B = np.array([64, 68, 54])
C = np.array([12, 14, 16])

pengurangan = A - B - C
print(pengurangan)

[-61 -73 -65]


In [7]:
# Transpose matrix

import numpy as np

A = np.array([[15, 9, 5], [64, 68, 54], [12, 14, 16]])

transpose_A = np.transpose(A)
print(transpose_A)

[[15 64 12]
 [ 9 68 14]
 [ 5 54 16]]


In [10]:
# Nilai invers

import numpy as np

A = np.array([[15, 9, 5], [64, 68, 54], [12, 14, 16]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

inverse_A = np.linalg.inv(A)
print("\nInvers matriks A:")
print(inverse_A)

Determinan dari matriks A: 1995.9999999999989

Invers matriks A:
[[ 0.16633267 -0.03707415  0.07314629]
 [-0.18837675  0.09018036 -0.24549098]
 [ 0.04008016 -0.0511022   0.22244489]]


In [11]:
# Nilai determinan

import numpy as np

A = np.array([[15, 9, 5], [64,68,54], [12, 14, 16]])

determinant_A = np.linalg.det(A)
print("Determinan dari matriks A:", determinant_A)

Determinan dari matriks A: 1995.9999999999989


In [4]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install seaborn

  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 393.8 kB/s eta 0:00:30
   ---------------------------------------- 0.1/11.5 MB 751.6 kB/s eta 0:00:16
    --------------------------------------- 0.3/11.5 MB 1.8 MB/s eta 0:00:07
   - -------------------------------------- 0.5/11.5 MB 2.2 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/11.5 MB 2.2 MB/s eta 0:00:05
   -- ------------------------------------- 0.7/11.5 MB 2.1 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/11.5 MB 2.1 MB/s eta 0:

## Latihan Library

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

usia = [20,22,21,23,20,22,21,24,23,20,22,21,23,20,22,21,24,23,20,22,21,23,20,22,21,24,23,20,22,21]
gender = [1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,1]

# Histogram 